[GEAR-319] UTH Request
scitran-apps/freesurfer-recon-all pull request #27
Opened 2020-03-17 19:03 UTC by joshicola

Incorporating UTH requests into recon-all.

2020-03-18 20:26 UTC, joshicola commented
Subj is retrieved from hierarchy, see cancelled job:
https://ss.ce.flywheel.io/#/jobslog/job/5e728125529e1613b8812db5

2020-03-19 05:31 UTC, lmperry requested changes
One change requested around license parsing from project context (`info`).

2020-03-19 05:31 UTC, lmperry commented on bin/parse_config.py
> +                option_string += '-openmp ' + str(max_cpus)
NIce.

2020-03-19 05:31 UTC, lmperry commented on bin/parse_config.py
> +        project_license = project.get_file('license.txt')
This is a completely sensible option, however it's not one of the [three "accepted" ways of providing a license](https://docs.flywheel.io/hc/en-us/articles/360013235453-How-to-include-a-Freesurfer-license-file-in-order-to-run-a-Freesurfer-or-fMRIPrep-gear-) (though it really should be). 
The third option is to provide the license as project context, or `info` on the project, and grab it from there: ```project.info.get('FREESURFER_LICENSE')```. Full example [here](https://github.com/flywheel-apps/fmriprep/blob/5.6.1_1.1.4/fs_license.py#L30-L36).

2020-03-19 16:00 UTC, joshicola commented on bin/parse_config.py
> +        project_license = project.get_file('license.txt')
I will make it an option.

2020-03-20 00:05 UTC, lmperry approved these changes

2020-03-20 00:06 UTC, merged